
var seatData= {
  "film_data_third_party_seat_map_response": {
    "result": {
      "return_code": "0",
      "return_value": {
        "max_can_buy": 5,
        "max_column": 20,
        "max_row": 9,
        "min_column": 1,
        "min_row": 1,
        "notice": "1、选座票由m1905提供，客服热线:0571-88157838\n2、请确认场次和时间无误，购买成功后将不予退换\n3、由于设备故障等不可抗力因素，存在少量场次取消的情况，会进行退票退款\n4、由于影院系统不稳定等因素，存在出票失败的情况，会进行退款",
        "regular": true,
        "seat_count": 114,
        "seats": {
          "seat": [
            {
              "column": 5,
              "ext_id": "3111",
              "flag": 1,
              "left_px": 150,
              "name": "1排12座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 6,
              "ext_id": "3112",
              "flag": 2,
              "left_px": 180,
              "name": "1排11座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 7,
              "ext_id": "3113",
              "flag": 0,
              "left_px": 210,
              "name": "1排10座",
              "row": 1,
              "row_name": "1",
              "status": 0,
              "top_px": 30
            },
            {
              "column": 8,
              "ext_id": "3114",
              "flag": 0,
              "left_px": 240,
              "name": "1排9座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 9,
              "ext_id": "3115",
              "flag": 0,
              "left_px": 270,
              "name": "1排8座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 10,
              "ext_id": "3116",
              "flag": 0,
              "left_px": 300,
              "name": "1排7座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 11,
              "ext_id": "3117",
              "flag": 0,
              "left_px": 330,
              "name": "1排6座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 12,
              "ext_id": "3118",
              "flag": 0,
              "left_px": 360,
              "name": "1排5座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 13,
              "ext_id": "3119",
              "flag": 0,
              "left_px": 390,
              "name": "1排4座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 14,
              "ext_id": "3120",
              "flag": 0,
              "left_px": 420,
              "name": "1排3座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 15,
              "ext_id": "3121",
              "flag": 0,
              "left_px": 450,
              "name": "1排2座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 16,
              "ext_id": "3122",
              "flag": 0,
              "left_px": 480,
              "name": "1排1座",
              "row": 1,
              "row_name": "1",
              "status": 1,
              "top_px": 30
            },
            {
              "column": 5,
              "ext_id": "3123",
              "flag": 0,
              "left_px": 150,
              "name": "2排12座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 6,
              "ext_id": "3124",
              "flag": 0,
              "left_px": 180,
              "name": "2排11座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 7,
              "ext_id": "3125",
              "flag": 0,
              "left_px": 210,
              "name": "2排10座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 8,
              "ext_id": "3126",
              "flag": 0,
              "left_px": 240,
              "name": "2排9座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 9,
              "ext_id": "3127",
              "flag": 0,
              "left_px": 270,
              "name": "2排8座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 10,
              "ext_id": "3128",
              "flag": 0,
              "left_px": 300,
              "name": "2排7座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 11,
              "ext_id": "3129",
              "flag": 0,
              "left_px": 330,
              "name": "2排6座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 12,
              "ext_id": "3130",
              "flag": 0,
              "left_px": 360,
              "name": "2排5座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 13,
              "ext_id": "3131",
              "flag": 0,
              "left_px": 390,
              "name": "2排4座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 14,
              "ext_id": "3132",
              "flag": 0,
              "left_px": 420,
              "name": "2排3座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 15,
              "ext_id": "3133",
              "flag": 0,
              "left_px": 450,
              "name": "2排2座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 16,
              "ext_id": "3134",
              "flag": 0,
              "left_px": 480,
              "name": "2排1座",
              "row": 2,
              "row_name": "2",
              "status": 1,
              "top_px": 60
            },
            {
              "column": 5,
              "ext_id": "3135",
              "flag": 0,
              "left_px": 150,
              "name": "3排12座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 6,
              "ext_id": "3136",
              "flag": 0,
              "left_px": 180,
              "name": "3排11座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 7,
              "ext_id": "3137",
              "flag": 0,
              "left_px": 210,
              "name": "3排10座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 8,
              "ext_id": "3138",
              "flag": 0,
              "left_px": 240,
              "name": "3排9座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 9,
              "ext_id": "3139",
              "flag": 0,
              "left_px": 270,
              "name": "3排8座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 10,
              "ext_id": "3140",
              "flag": 0,
              "left_px": 300,
              "name": "3排7座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 11,
              "ext_id": "3141",
              "flag": 0,
              "left_px": 330,
              "name": "3排6座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 12,
              "ext_id": "3142",
              "flag": 0,
              "left_px": 360,
              "name": "3排5座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 13,
              "ext_id": "3143",
              "flag": 0,
              "left_px": 390,
              "name": "3排4座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 14,
              "ext_id": "3144",
              "flag": 0,
              "left_px": 420,
              "name": "3排3座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 15,
              "ext_id": "3145",
              "flag": 0,
              "left_px": 450,
              "name": "3排2座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 16,
              "ext_id": "3146",
              "flag": 0,
              "left_px": 480,
              "name": "3排1座",
              "row": 3,
              "row_name": "3",
              "status": 1,
              "top_px": 90
            },
            {
              "column": 5,
              "ext_id": "3147",
              "flag": 0,
              "left_px": 150,
              "name": "4排12座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 6,
              "ext_id": "3148",
              "flag": 0,
              "left_px": 180,
              "name": "4排11座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 7,
              "ext_id": "3149",
              "flag": 0,
              "left_px": 210,
              "name": "4排10座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 8,
              "ext_id": "3150",
              "flag": 0,
              "left_px": 240,
              "name": "4排9座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 9,
              "ext_id": "3151",
              "flag": 0,
              "left_px": 270,
              "name": "4排8座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 10,
              "ext_id": "3152",
              "flag": 0,
              "left_px": 300,
              "name": "4排7座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 11,
              "ext_id": "3153",
              "flag": 0,
              "left_px": 330,
              "name": "4排6座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 12,
              "ext_id": "3154",
              "flag": 0,
              "left_px": 360,
              "name": "4排5座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 13,
              "ext_id": "3155",
              "flag": 0,
              "left_px": 390,
              "name": "4排4座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 14,
              "ext_id": "3156",
              "flag": 0,
              "left_px": 420,
              "name": "4排3座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 15,
              "ext_id": "3157",
              "flag": 0,
              "left_px": 450,
              "name": "4排2座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 16,
              "ext_id": "3158",
              "flag": 0,
              "left_px": 480,
              "name": "4排1座",
              "row": 4,
              "row_name": "4",
              "status": 1,
              "top_px": 120
            },
            {
              "column": 5,
              "ext_id": "3159",
              "flag": 0,
              "left_px": 150,
              "name": "5排14座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 6,
              "ext_id": "3160",
              "flag": 0,
              "left_px": 180,
              "name": "5排13座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 7,
              "ext_id": "3161",
              "flag": 0,
              "left_px": 210,
              "name": "5排12座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 8,
              "ext_id": "3162",
              "flag": 0,
              "left_px": 240,
              "name": "5排11座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 9,
              "ext_id": "3163",
              "flag": 0,
              "left_px": 270,
              "name": "5排10座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 10,
              "ext_id": "3164",
              "flag": 0,
              "left_px": 300,
              "name": "5排9座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 11,
              "ext_id": "3165",
              "flag": 0,
              "left_px": 330,
              "name": "5排8座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 12,
              "ext_id": "3166",
              "flag": 0,
              "left_px": 360,
              "name": "5排7座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 13,
              "ext_id": "3167",
              "flag": 0,
              "left_px": 390,
              "name": "5排6座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 14,
              "ext_id": "3168",
              "flag": 0,
              "left_px": 420,
              "name": "5排5座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 15,
              "ext_id": "3169",
              "flag": 0,
              "left_px": 450,
              "name": "5排4座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 16,
              "ext_id": "3170",
              "flag": 0,
              "left_px": 480,
              "name": "5排3座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 19,
              "ext_id": "3171",
              "flag": 0,
              "left_px": 570,
              "name": "5排2座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 20,
              "ext_id": "3172",
              "flag": 0,
              "left_px": 600,
              "name": "5排1座",
              "row": 5,
              "row_name": "5",
              "status": 1,
              "top_px": 150
            },
            {
              "column": 3,
              "ext_id": "3173",
              "flag": 0,
              "left_px": 90,
              "name": "6排16座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 4,
              "ext_id": "3174",
              "flag": 0,
              "left_px": 120,
              "name": "6排15座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 5,
              "ext_id": "3175",
              "flag": 0,
              "left_px": 150,
              "name": "6排14座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 6,
              "ext_id": "3176",
              "flag": 0,
              "left_px": 180,
              "name": "6排13座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 7,
              "ext_id": "3177",
              "flag": 0,
              "left_px": 210,
              "name": "6排12座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 8,
              "ext_id": "3178",
              "flag": 0,
              "left_px": 240,
              "name": "6排11座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 9,
              "ext_id": "3179",
              "flag": 0,
              "left_px": 270,
              "name": "6排10座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 10,
              "ext_id": "3180",
              "flag": 0,
              "left_px": 300,
              "name": "6排9座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 11,
              "ext_id": "3181",
              "flag": 0,
              "left_px": 330,
              "name": "6排8座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 12,
              "ext_id": "3182",
              "flag": 0,
              "left_px": 360,
              "name": "6排7座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 13,
              "ext_id": "3183",
              "flag": 0,
              "left_px": 390,
              "name": "6排6座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 14,
              "ext_id": "3184",
              "flag": 0,
              "left_px": 420,
              "name": "6排5座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 15,
              "ext_id": "3185",
              "flag": 0,
              "left_px": 450,
              "name": "6排4座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 16,
              "ext_id": "3186",
              "flag": 0,
              "left_px": 480,
              "name": "6排3座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 19,
              "ext_id": "3187",
              "flag": 0,
              "left_px": 570,
              "name": "6排2座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 20,
              "ext_id": "3188",
              "flag": 0,
              "left_px": 600,
              "name": "6排1座",
              "row": 6,
              "row_name": "6",
              "status": 1,
              "top_px": 180
            },
            {
              "column": 3,
              "ext_id": "3189",
              "flag": 0,
              "left_px": 90,
              "name": "7排16座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 4,
              "ext_id": "3190",
              "flag": 0,
              "left_px": 120,
              "name": "7排15座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 5,
              "ext_id": "3191",
              "flag": 0,
              "left_px": 150,
              "name": "7排14座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 6,
              "ext_id": "3192",
              "flag": 0,
              "left_px": 180,
              "name": "7排13座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 7,
              "ext_id": "3193",
              "flag": 0,
              "left_px": 210,
              "name": "7排12座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 8,
              "ext_id": "3194",
              "flag": 0,
              "left_px": 240,
              "name": "7排11座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 9,
              "ext_id": "3195",
              "flag": 0,
              "left_px": 270,
              "name": "7排10座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 10,
              "ext_id": "3196",
              "flag": 0,
              "left_px": 300,
              "name": "7排9座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 11,
              "ext_id": "3197",
              "flag": 0,
              "left_px": 330,
              "name": "7排8座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 12,
              "ext_id": "3198",
              "flag": 0,
              "left_px": 360,
              "name": "7排7座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 13,
              "ext_id": "3199",
              "flag": 0,
              "left_px": 390,
              "name": "7排6座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 14,
              "ext_id": "3200",
              "flag": 0,
              "left_px": 420,
              "name": "7排5座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 15,
              "ext_id": "3201",
              "flag": 0,
              "left_px": 450,
              "name": "7排4座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 16,
              "ext_id": "3202",
              "flag": 0,
              "left_px": 480,
              "name": "7排3座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 19,
              "ext_id": "3203",
              "flag": 0,
              "left_px": 570,
              "name": "7排2座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 20,
              "ext_id": "3204",
              "flag": 0,
              "left_px": 600,
              "name": "7排1座",
              "row": 7,
              "row_name": "7",
              "status": 1,
              "top_px": 210
            },
            {
              "column": 1,
              "ext_id": "3205",
              "flag": 0,
              "left_px": 30,
              "name": "8排20座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 2,
              "ext_id": "3206",
              "flag": 0,
              "left_px": 60,
              "name": "8排19座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 3,
              "ext_id": "3207",
              "flag": 0,
              "left_px": 90,
              "name": "8排18座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 4,
              "ext_id": "3208",
              "flag": 0,
              "left_px": 120,
              "name": "8排17座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 5,
              "ext_id": "3209",
              "flag": 0,
              "left_px": 150,
              "name": "8排16座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 6,
              "ext_id": "3210",
              "flag": 0,
              "left_px": 180,
              "name": "8排15座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 7,
              "ext_id": "3211",
              "flag": 0,
              "left_px": 210,
              "name": "8排14座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 8,
              "ext_id": "3212",
              "flag": 0,
              "left_px": 240,
              "name": "8排13座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 9,
              "ext_id": "3213",
              "flag": 0,
              "left_px": 270,
              "name": "8排12座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 10,
              "ext_id": "3214",
              "flag": 0,
              "left_px": 300,
              "name": "8排11座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 11,
              "ext_id": "3215",
              "flag": 0,
              "left_px": 330,
              "name": "8排10座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 12,
              "ext_id": "3216",
              "flag": 0,
              "left_px": 360,
              "name": "8排9座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 13,
              "ext_id": "3217",
              "flag": 0,
              "left_px": 390,
              "name": "8排8座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 14,
              "ext_id": "3218",
              "flag": 0,
              "left_px": 420,
              "name": "8排7座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 15,
              "ext_id": "3219",
              "flag": 0,
              "left_px": 450,
              "name": "8排6座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 16,
              "ext_id": "3220",
              "flag": 0,
              "left_px": 480,
              "name": "8排5座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 17,
              "ext_id": "3221",
              "flag": 0,
              "left_px": 510,
              "name": "8排4座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 18,
              "ext_id": "3222",
              "flag": 0,
              "left_px": 540,
              "name": "8排3座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 19,
              "ext_id": "3223",
              "flag": 0,
              "left_px": 570,
              "name": "8排2座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 20,
              "ext_id": "3224",
              "flag": 0,
              "left_px": 600,
              "name": "8排1座",
              "row": 8,
              "row_name": "8",
              "status": 1,
              "top_px": 240
            },
            {
              "column": 10,
              "ext_id": "3224",
              "flag": 0,
              "left_px": 510,
              "name": "9排1座",
              "row": 9,
              "row_name": "8",
              "status": 1,
              "top_px": 270
            },
            {
              "column": 15,
              "ext_id": "3224",
              "flag": 0,
              "left_px": 540,
              "name": "9排2座",
              "row": 9,
              "row_name": "8",
              "status": 1,
              "top_px": 270
            }
          ]
        },
        "sold_count": 0,
        "tip_message": "您选择的是<b>周五 09-15</b>的场次，请看仔细哦"
      }
    },
    "request_id": "15a02gpqcy9ci"
  }
}

const max_column = seatData.film_data_third_party_seat_map_response.result.return_value.max_column
const max_row = seatData.film_data_third_party_seat_map_response.result.return_value.max_row
const seats = seatData.film_data_third_party_seat_map_response.result.return_value.seats.seat

export { seatData, seats, max_column, max_row };